# Configuration for Support Requests - https://github.com/dessant/support-requests

# Label used to mark issues as support requests
supportLabel: repro-required

# Comment to post on issues marked as support requests, `{issue-author}` is an
# optional placeholder. Set to `false` to disable
supportComment: >
  :wave: @{issue-author}, sorry you're having an issue. As the issue template explains, we require that you provide a runnable example that reproduces your issue (please read the [issue template](https://raw.githubusercontent.com/react-native-community/google-signin/master/.github/ISSUE_TEMPLATE/Custom.md)).

  The reason is that maintainers do not have time to try reproduce bugs themselves. Please try to minimize the superfluous code and focus only on reproducing the bug.
  
  Please create a new issue with this and we'll be happy to review it! If you're hitting a hard wall, you may consider [paid assistance](https://github.com/react-native-community/google-signin/pull/861).

# Close issues marked as support requests
close: true

# Lock issues marked as support requests
lock: true

# Assign `off-topic` as the reason for locking. Set to `false` to disable
setLockReason: true

# Repository to extend settings from
# _extends: repo 